# Generated by Django 3.2.16 on 2023-01-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_blog', '0002_auto_20230104_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
